security:
    encoders:
        App\Entity\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main

            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: home
            logout:
                path: fos_user_security_logout
                target: homepage
            logout_on_user_change: true
    access_control:
            - { path: ^/admin, roles: [ROLE_USER,ROLE_ADMIN] }